dataset: sc-classification
layer: s4
seed: 1

model:
  d_model: 128
  n_layers: 4
  dropout: 0.25
  prenorm: true
  embedding: false
  layer:
    'N': 64

train:
  epochs: 20
  bsz: 16
  lr: 0.005
  lr_schedule: true
  weight_decay: 0.01
  checkpoint: false
  suffix: null
  sample: null

wandb:
  mode: disabled
  project: s4
  entity: null